name: SurvivalGames
main: net.dmulloy2.survivalgames.SurvivalGames
version: ${project.version}${project.build.number}
author: dmulloy2
description: Fully Automated Hunger Games Plugin!
softdepend: [Multiverse-Core, WorldEdit]

commands:
  survivalgames:
    description: Survival Games Command
    usage: /sg <command> <args>
    aliases: [sg, hungergames, hg]

permissions:
# Player Permissions
  sg.player.*:
    default: true
    description: SurvivalGames player commands
    children:
      sg.player.list: true
      sg.player.listarenas: true
      sg.player.join: true
      sg.player.join.lobby: true
      sg.player.spectate: true
      sg.player.version: true
      sg.player.vote: true
      sg.arenas.join.*: true
  sg.player.list:
    description: Allows access to '/sg list'
    default: true
  sg.player.listarenas:
    description: Allows access to '/sg listarenas'
    default: true
  sg.player.join:
    description: Allows access to '/sg join'
    default: true
  sg.player.join.lobby:
    description: Allows the joining of lobbies
    default: true
  sg.player.spectate:
    description: Allows access to '/sg spectate'
    default: true
  sg.player.version:
    description: Allows access to '/sg version'
    default: true
  sg.player.vote:
    description: Allows access to '/sg vote'
    default: true
  sg.arenas.join.*:
    description: Allows the joining of all arenas
    default: true

# Staff Permissions
  sg.staff.*:
    description: SurvivalGames staff commands
    children:
      sg.player.*: true
      sg.staff.enable: true
      sg.staff.disable: true
      sg.staff.teleport: true
  sg.staff.enable:
    description: Allows access to '/sg enable'
    default: false
  sg.staff.disable:
    description: Allows access to '/sg disable'
    default: false
  sg.staff.teleport:
    description: Allows access to '/sg teleport'
    default: false

# Admin Permissions
  sg.admin.*:
    default: op
    description: SurvivalGames admin commands
    children:
      sg.admin.addwall: true
      sg.admin.createarena: true
      sg.admin.forcestart: true
      sg.admin.flag: true
      sg.admin.delarena: true
      sg.admin.reload: true
      sg.admin.resetspawns: true
      sg.admin.setlobbyspawn: true
      sg.admin.setspawn: true
  sg.admin.addwall:
    description: Allows access to '/sg addwall'
    default: false
  sg.admin.createarena:
    description: Allows access to '/sg createarena'
    default: false
  sg.admin.forcestart:
    description: Allows access to '/sg forcestart'
    default: false
  sg.admin.flag:
    description: Allows access to '/sg flag'
    default: false
  sg.admin.delarena:
    description: Allows access to '/sg delarena'
    default: false
  sg.admin.reload:
    description: Allows access to '/sg reload'
    default: false
  sg.admin.resetspawns:
    description: Allows access to '/sg resetspawns'
    default: false
  sg.admin.setlobbyspawn:
    description: Allows access to '/sg setlobbyspawn'
    default: false
  sg.admin.setspawn:
    description: Allows access to '/sg setspawn'
    default: false